Model usage update
allenai/allennlp-demo pull request #795
Opened 2021-02-04 23:08 UTC by AkshitaB

- Update Dockerfile so that commit SHA can be specified for allennlp and allennlp-models.
- Update ModelUsage and various Usage files.

2021-02-04 23:52 UTC, epwalsh commented on api/requirements.txt
>  allennlp-semparse==0.0.2
I think we'll need to pin this to a commit, or do another semparse release that allows for allennlp>=2.0

2021-02-04 23:53 UTC, epwalsh reviewed
LGTM, other than the issue with semparse

2021-02-05 17:03 UTC, jonborchardt requested changes
great work!
left some ideas... let me know if anything is unclear

2021-02-05 17:03 UTC, jonborchardt commented on ui/src/components/ModelUsage.tsx
> +const DatasetLink = ({ link }: { link: Link }) => {
this already exists in the code somewhere... we should move to a shared location and not have 2 copies

2021-02-05 17:03 UTC, jonborchardt commented on ui/src/tugboat/lib/ModelCard.ts
> +    processed_url?: any;
what is a processed url?

2021-02-05 19:15 UTC, AkshitaB commented on api/allennlp_demo/model_cards/requirements.txt
> +git+git://github.com/allenai/allennlp.git@4535f5c84462ee1bc673df60a1afc35c7913cf55
You would prefer a release?

2021-02-05 19:28 UTC, jonborchardt commented on api/allennlp_demo/model_cards/requirements.txt
> +git+git://github.com/allenai/allennlp.git@4535f5c84462ee1bc673df60a1afc35c7913cf55
yes, is that ok?

2021-02-05 19:32 UTC, AkshitaB commented on api/allennlp_demo/model_cards/requirements.txt
> +git+git://github.com/allenai/allennlp.git@4535f5c84462ee1bc673df60a1afc35c7913cf55
Well, it would be preferable to not require a release each time. But I'll defer to your opinion.

2021-02-05 19:38 UTC, jonborchardt commented on api/allennlp_demo/model_cards/requirements.txt
> +git+git://github.com/allenai/allennlp.git@4535f5c84462ee1bc673df60a1afc35c7913cf55
ya... i suggest you get pete you dirk and schmitz in a room and decide how you want to do model card releases....

2021-02-05 19:48 UTC, AkshitaB commented on ui/src/components/ModelUsage.tsx
> +            ) : <p>Evaluation command is unavailable.</p>}
The evaluation notes may include information other than whether the command is available or not. If the command itself is missing, we do want to show this.

2021-02-05 19:49 UTC, AkshitaB commented on ui/src/components/ModelUsage.tsx
> +            ) : <p>Training command is unavailable.</p>}
Same as above for the explanation.

2021-02-05 19:50 UTC, AkshitaB commented on ui/src/tugboat/lib/ModelCard.ts
> +    processed_url?: any;
`processed_url` is the link to use in the evaluation command; the processed dataset ready for use in allennlp. The regular url is a pointer to the dataset webpage/information. I would like the model cards to remain as general as possible.

2021-02-05 19:55 UTC, jonborchardt commented on ui/src/components/ModelUsage.tsx
> +            ) : <p>Evaluation command is unavailable.</p>}
i meant...
only display `Evaluation command is unavailable.` if both command AND note are null

2021-02-05 19:56 UTC, jonborchardt commented on ui/src/tugboat/lib/ModelCard.ts
> +    processed_url?: any;
can you rename this interface something other than Link.... its no longer a Link ;-P

2021-02-05 20:35 UTC, schmmd commented on api/allennlp_demo/model_cards/requirements.txt
> +git+git://github.com/allenai/allennlp.git@4535f5c84462ee1bc673df60a1afc35c7913cf55
@epwalsh, @dirkgr, @AkshitaB and I previously discussed this and we're fine depending on a SHA.

2021-02-05 23:25 UTC, jonborchardt reviewed
just a few more things to clean up

2021-02-05 23:25 UTC, jonborchardt commented on ui/src/components/ModelUsage.tsx
> +        -s /path/to/output`.trim();
i dont think these trims are needed... but they are not hurting either.

2021-02-05 23:25 UTC, jonborchardt commented on ui/src/components/ModelUsage.tsx
> +                <p>Evaluation command is unavailable.</p>
we should only show this if !evaluationCommand&&props.modelCard.evaluation_dataset.notes
or we need a label for the sub-sections

del ln 72
del ln75
wrap ln 73 with h6

add a line under 77
`<h6>Command:</h6>`

2021-02-05 23:25 UTC, jonborchardt commented on ui/src/components/ModelUsage.tsx
> +                <p>Training command is unavailable.</p>
same notes as above....

2021-02-05 23:25 UTC, jonborchardt commented on ui/src/components/ModelUsage.tsx
> +const DatasetLink = ({ link }: { link: Link }) => {
did you find the other code that does this?

2021-02-05 23:25 UTC, jonborchardt commented on ui/src/tugboat/lib/ModelCard.ts
> +    processed_url?: any;
please rename this interface

2021-02-05 23:25 UTC, jonborchardt commented on ui/src/components/ModelUsage.tsx
> +const DatasetLink = ({ link }: { link: Link }) => {
it is in modelcard.tsx called MaybeLink
please move it to togboat/components/MaybeLink.tsx
(it will take the following Props (not the new link you are using))
```
interface Props {	
    name: string;	  
    url?: any;
}
```

2021-02-06 00:02 UTC, AkshitaB commented on ui/src/components/ModelUsage.tsx
> +        -s /path/to/output`.trim();
I found that the the trims _are_ required.

2021-02-06 00:21 UTC, jonborchardt reviewed
few things left

2021-02-06 00:21 UTC, jonborchardt commented on ui/src/components/ModelUsage.tsx
> +                    About the dataset: <DatasetLink link={props.modelCard.evaluation_dataset} />
there was a miss-communication
please remove this h6

2021-02-06 00:21 UTC, jonborchardt commented on ui/src/components/ModelUsage.tsx
> +                <h6>
please remove this h6

2021-02-06 00:21 UTC, jonborchardt commented on ui/src/components/ModelUsage.tsx
> +            {!(evaluationCommand && props.modelCard.evaluation_dataset.notes) ? (
```suggestion
            {(!evaluationCommand && !props.modelCard.evaluation_dataset.notes) ? (
```

2021-02-06 00:21 UTC, jonborchardt commented on ui/src/components/ModelUsage.tsx
> +            {!(trainingCommand && props.modelCard.training_dataset.notes) ? (
```suggestion
            {(!trainingCommand && !props.modelCard.training_dataset.notes) ? (
```

2021-02-06 00:21 UTC, jonborchardt commented on ui/src/components/ModelUsage.tsx
> +const DatasetLink = ({ link }: { link: Link }) => {
?? can this be done in this pr?

2021-02-06 00:21 UTC, jonborchardt commented on ui/src/tugboat/lib/ModelCard.ts
> +    processed_url?: any;
can this be done in this pr?

2021-02-06 00:48 UTC, AkshitaB commented on ui/src/components/ModelUsage.tsx
> +                <h6>
And replace it with <p> ?

2021-02-06 02:12 UTC, jonborchardt approved these changes

2021-02-06 04:12 UTC, merged